### ISSUE TITLE
Upgrade cassandra-stress test to python 3.

### ISSUE THREAD

**Issue by Victor-martinelli** [GoogleCloudPlatform/PerfKitBenchmarker#2053]
I ran some tests successfully (ping and cassandra_cassandra_ycsb) but when trying to run cassandra_stress with default configuration, I get the following error:

`2019-12-06 13:42:23,777 0cddc950 MainThread cassandra_stress(1/1) background_tasks.py:545 ERROR    Exception occurred while calling RunTestOnLoader(34.70.55.103, 0, 1, [u'10.128.0.3', u'10.128.0.4', u'10.128.0.2'], write, insert=1, 1.0, None, None):
Traceback (most recent call last):
  File "/home/factory/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 255, in Run
    self.return_value = self.target(*self.args, **self.kwargs)
  File "/home/factory/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/cassandra_stress_benchmark.py", line 404, in RunTestOnLoader
    threads=FLAGS.num_cassandra_stress_threads))
  File "/home/factory/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 281, in RobustRemoteCommand
    return _WaitForCommand()
  File "/home/factory/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 278, in _WaitForCommand
    ignore_failure=ignore_failure)
  File "/home/factory/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 724, in RemoteCommand
    return self.RemoteCommandWithReturnCode(*args, **kwargs)[:2]
  File "/home/factory/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 740, in RemoteCommandWithReturnCode
    return self.RemoteHostCommandWithReturnCode(*args, **kwargs)
  File "/home/factory/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 812, in RemoteHostCommandWithReturnCode
    raise errors.VirtualMachine.RemoteCommandError(error_text)
RemoteCommandError: Got non-zero return code (1) executing python /tmp/pkb/wait_for_command.py --status /tmp/pkb/cmd0f419fc8-ddb3-4f79-97f7-a259688defb1.status --stdout /tmp/pkb/cmd0f419fc8-ddb3-4f79-97f7-a259688defb1.stdout --stderr /tmp/pkb/cmd0f419fc8-ddb3-4f79-97f7-a259688defb1.stderr --delete
Full command: ssh -A -p 22 perfkit@34.70.55.103 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /tmp/perfkitbenchmarker/runs/0cddc950/perfkitbenchmarker_keyfile -o ControlPath="/tmp/perfkitbenchmarker/runs/0cddc950/ssh/%h" -o ControlMaster=auto -o ControlPersist=30m python /tmp/pkb/wait_for_command.py --status /tmp/pkb/cmd0f419fc8-ddb3-4f79-97f7-a259688defb1.status --stdout /tmp/pkb/cmd0f419fc8-ddb3-4f79-97f7-a259688defb1.stdout --stderr /tmp/pkb/cmd0f419fc8-ddb3-4f79-97f7-a259688defb1.stderr --delete
STDOUT: Invalid value 1.0..1.0; must match pattern [0-9]+[MBK]?\.\.+[0-9]+[MBK]?`

My idea is that somewhere in the code, extra 'u's are getting added to the ip addresses and that's why I'm getting this error.

`2019-12-06 13:42:23,777 0cddc950 MainThread cassandra_stress(1/1) background_tasks.py:545 ERROR    Exception occurred while calling RunTestOnLoader(34.70.55.103, 0, 1, [u'10.128.0.3', u'10.128.0.4', u'10.128.0.2'], write, insert=1, 1.0, None, None):`

I've tried digging through the code but I haven't found the issue yet. Any help would be greatly appreciated.

The full logs are also attached here. 
[pkb.log](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/files/3933826/pkb.log)

Thanks in advance.

**Comment by yuyantingzero** [comment]
Quick question, are you running PKB with python3+? This particular benchmark seems to be outdated and may not work with python 3, can you try py2.7

More details:
Following command failed:
INFO:root:Started pid 16010: /opt/pkb/cassandra/tools/bin/cassandra-stress write cl=QUORUM n=1 -node 10.128.0.3,10.128.0.4,10.128.0.2 -schema replication\(factor=3\) -pop seq=1.0..1.0 -log file=/tmp/pkb/pkb-0cddc950-0.stress_results.txt -rate threads=150 -errors retries=1000

Stacktrace:
2019-12-06 13:42:23,634 0cddc950 Thread-268 cassandra_stress(1/1) vm_util.py:423 INFO     Ran: {ssh -A -p 22 perfkit@34.70.55.103 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /tmp/perfkitbenchmarker/runs/0cddc950/perfkitbenchmarker_keyfile -o ControlPath="/tmp/perfkitbenchmarker/runs/0cddc950/ssh/%h" -o ControlMaster=auto -o ControlPersist=30m python /tmp/pkb/wait_for_command.py --status /tmp/pkb/cmd0f419fc8-ddb3-4f79-97f7-a259688defb1.status --stdout /tmp/pkb/cmd0f419fc8-ddb3-4f79-97f7-a259688defb1.stdout --stderr /tmp/pkb/cmd0f419fc8-ddb3-4f79-97f7-a259688defb1.stderr --delete}
ReturnCode:1
STDOUT: Invalid value 1.0..1.0; must match pattern [0-9]+[MBK]?\.\.+[0-9]+[MBK]?

If I understand correctly, this is caused by https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/a2e48f4a8a0f40a82a989d43d9b017d7d7b292c3/perfkitbenchmarker/linux_benchmarks/cassandra_stress_benchmark.py#L428, which should produce an Int in python2, but in python3+, this is a float.

I would suggest running with python 2 for now if you would like to try this benchmark.
