### PR TITLE
Fix spurious -Wmaybe-uninitialized error in silo

### PR DESCRIPTION
**Pull request by peterfeiner**
The silo package fails to build with g++ 4.9.2 because of a 'maybe
uninitialized' error:

  Makefile:197: recipe for target 'out-perf.masstree/json.o' failed
  STDERR: Warning: Permanently added '127.0.0.1' (ECDSA) to the list of known hosts.
  Cloning into 'masstree'...
  make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
  masstree/json.cc: In member function void lcdf::Json::hard_unparse(lcdf::StringAccum&, const lcdf::Json::unparse_manipulator&, int) const:
  masstree/json.cc:636:28: error: upx may be used uninitialized in this function [-Werror=maybe-uninitialized]
                   sa << upx[1];
                              ^
  masstree/json.cc:642:2: error: expanded may be used uninitialized in this function [-Werror=maybe-uninitialized]
    if (expanded)
    ^
  cc1plus: all warnings being treated as errors
  make: *** [out-perf.masstree/json.o] Error 1

This patch disables errors on this warning.

### CODE REVIEW

**Comment by peterfeiner** [comment]
Rolled into https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/1152.
